server.port=8095

spring.datasource.url=jdbc:mysql://mysql-checkin-checkout:3306/checkin_checkout_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.security.user.name=root
spring.security.user.password=1234