spring.application.name=api-gateway
server.port=8090

# Eureka local
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Discovery dinámico
spring.cloud.discovery.locator.enabled=true
spring.cloud.discovery.locator.lower-case-service-id=true


# Usuarios
spring.cloud.gateway.server.webmvc.routes[0].id=usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://usuarios
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/usuarios/**

# Clientes
spring.cloud.gateway.server.webmvc.routes[1].id=clientes
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://clientes
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/clientes/**

# Habitaciones
spring.cloud.gateway.server.webmvc.routes[2].id=habitaciones
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://habitaciones
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/habitaciones/**

# Reservas
spring.cloud.gateway.server.webmvc.routes[3].id=reservas
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://reservas
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/reservas/**

# Servicio Extra
spring.cloud.gateway.server.webmvc.routes[4].id=servicioextra
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://servicioextra
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/servicioextra/**

# Tipo Servicio
spring.cloud.gateway.server.webmvc.routes[5].id=tiposervicio
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://servicioextra
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/tiposervicio/**

# Consumo
spring.cloud.gateway.server.webmvc.routes[6].id=consumo
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://consumo
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/consumo/**

# Mantenimiento
spring.cloud.gateway.server.webmvc.routes[7].id=mantenimiento
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://mantenimiento
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/mantenimiento/**

# Notificaciones
spring.cloud.gateway.server.webmvc.routes[8].id=notificaciones
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://notificaciones
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/notificaciones/**

# Pagos
spring.cloud.gateway.server.webmvc.routes[9].id=pagos
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://pagos
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/pagos/**

# Reportes
spring.cloud.gateway.server.webmvc.routes[10].id=reportes
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://reportes
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/reportes/**