# Conexion MySQL local VSCode
spring.datasource.url=jdbc:mysql://localhost:3314/consumo_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URLs microservicios LOCAL
servicioextra.service.url=http://localhost:8083
cliente.service.url=http://localhost:8080
habitacion.service.url=http://localhost:8081
reserva.service.url=http://localhost:8082

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true