# Conexion Docker
spring.datasource.url=jdbc:mysql://db-consumo:3306/consumo_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URLs microservicios DOCKER
servicioextra.service.url=http://servicioextra-service:8083
cliente.service.url=http://clientes-service:8080
habitacion.service.url=http://habitaciones-service:8081
reserva.service.url=http://reservas-service:8082

# Eureka

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true