# Conexion MySQL DOCKER
spring.datasource.url=jdbc:mysql://db-pagos:3306/pagos_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Espera MySQL
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=60000

# URLs microservicios DOCKER
reservas.service.url=http://reservas-service:8082
consumos.service.url=http://consumo-service:8087

#Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true