# Conexion MySQL DOCKER
spring.datasource.url=jdbc:mysql://db-reservas:3306/reservas_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari espera MySQL
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=60000

# URLs microservicios DOCKER
clientes.service.url=http://clientes-service:8080
habitaciones.service.url=http://habitaciones-service:8081
notificaciones.service.url=http://notificaciones-service:8089

#Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true