# Conexion MySQL DOCKER
spring.datasource.url=jdbc:mysql://db-notificaciones:3306/notificaciones_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true