server.port=8090

spring.datasource.url=jdbc:mysql://mysql-usuarios:3306/usuarios_db
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

roles-service.url=http://roles-service:8092
login-service.url=http://login-service:8091