CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    nombre VARCHAR(100) NOT NULL,

    apellido VARCHAR(100) NOT NULL,

    username VARCHAR(100) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    correo VARCHAR(150) NOT NULL UNIQUE,

    rol VARCHAR(50) NOT NULL,

    activo BOOLEAN NOT NULL
);